name: EAS Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install -g eas-cli
      - run: eas login --token eqGBT9v67zRPyAzFagaC2POV4xOX-_Z04MenSGOI
      - run: eas build --platform all --auto-submit